# Generated by Django 5.2.1 on 2025-05-22 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickoff_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_time', models.DateTimeField()),
                ('number_of_passangers', models.IntegerField(default=1)),
                ('ride_type', models.CharField(choices=[('BIKE', 'bike'), ('CAR', 'car'), ('BUS', 'bus'), ('VAN', 'van')], default='bike', max_length=4)),
                ('ride_status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('IN_PROGRESS', 'in_Progress'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], max_length=11)),
                ('number_of_rides', models.IntegerField(default=1)),
                ('special_request', models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default='no', max_length=3, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
