# Generated by Django 5.2.1 on 2025-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('DRIVER', 'driver'), ('RIDER', 'rider')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('STAFF', 'staff'), ('ADMIN', 'admin'), ('OPERATORS', 'operators')], default='CUSTOMER', max_length=9),
        ),
    ]
