# Generated by Django 5.2.1 on 2025-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_staff_role_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_secret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
