# Generated by Django 5.2.1 on 2025-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
