# Generated by Django 5.2.1 on 2025-06-10 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_pendinguser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'customer'), ('STAFF', 'staff'), ('ADMIN', 'admin'), ('OPERATORS', 'operators')], default='CUSTOMER', max_length=9)),
                ('staff_role', models.CharField(blank=True, choices=[('DRIVER', 'driver'), ('RIDER', 'rider')], max_length=20, null=True)),
                ('admin_secret', models.CharField(blank=True, max_length=14, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('STAFF', 'staff'), ('ADMIN', 'admin'), ('OPERATORS', 'operators')], default='STAFF', max_length=9),
        ),
    ]
