# Generated by Django 5.2.1 on 2025-06-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_pendingstaff_alter_pendinguser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingstaff',
            name='is_active',
        ),
    ]
