# Generated by Django 5.2.1 on 2025-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitymodel',
            name='signin_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
