# Generated by Django 5.2.1 on 2025-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_availabilitymodel_signin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitymodel',
            name='titled_name',
            field=models.CharField(blank=True, max_length=259, null=True),
        ),
    ]
